export const orderWaiting = [
    {
        name:'Structure',
        fieldName:'name_structure',
        display:true,
    },
    {
        name:'Academy',
        fieldName:'structure.academy',
        display:true,
    },
    {
        name:'lystore.structure.type',
        fieldName:'structure.type',
        display:true,
    },
    {
        name:'contract',
        fieldName:'contract.name',
        display:true,
    },
    {
        name:'lystore.contract.type.name',
        fieldName:'contract_type.name',
        display:true,
    },
    {
        name:'lystore.project',
        fieldName:'project.title.name',
        display:true,
    },
    {
        name:'EQUIPMENT',
        fieldName:'supplier.name',
        display:false,
    },
    {
        name:'lystore.amount',
        fieldName:'amount',
        display:false,
    },
    {
        name:'date',
        fieldName:'id',
        display:false,
    },
    {
        name:'STRUCTUREGROUP',
        fieldName:'structure_groups',
        display:false,
    },
    {
        name:'lystore.campaigns',
        fieldName:'campaign.name',
        display:false,
    },
    {
        name:'lystore.project.preference',
        fieldName:'project.preference',
        display:false,
    },
    {
        name:'lystore.order.rank',
        fieldName:'rank',
        display:false,
    },
    {
        name:'lystore.price.TTC',
        fieldName:'priceTTCtotal',
        display:true,
    }
];